# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: kayam-habit-builder-staging
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  memorySize: 1024
  stage: dev
  timeout: 15
  region: us-east-1
  runtime: nodejs16.x
  apiGateway:
    restApiId: 7dsz7mm13j
    restApiRootResourceId: 9j57dbimk1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: habits/categories
          method: GET
      - http:
          path: habits/challenges
          method: GET
      - http:
          path: habits/start-challenge
          method: POST
      - http:
          path: habits/update-userchallenge
          method: PUT
      - http:
          path: habits/all-user-challenges
          method: GET
      - http:
          path: habits/user-challenges
          method: POST
      - http:
          path: habits/notification-status
          method: PUT
    environment:
      PORT: 4000
      DATABASE_URL: "mysql://admin:kayam123kayam123@kayam-habit-builder-staging.colgsq2adoyw.us-east-1.rds.amazonaws.com:3306/prisma"

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'